services:

  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-""}
      REDIS_SAVE: ${REDIS_SAVE_IN_SECONDS:-3600}
      REDIS_DB: ${REDIS_DB:-0}
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - internal-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: on-failure
    environment:
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE:-"disable"}
      POSTGRES_USER: ${POSTGRES_USERNAME-"postgres"}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-"root"}
      POSTGRES_DB: ${POSTGRES_DATABASE:-"test"}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal-network

  api:
    container_name: api
    build:
      context: .
      target: api
      dockerfile: ./docker/api/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "13100:3100"
    networks:
      - internal-network

networks:
  internal-network:
    name: go-network
    driver: bridge

volumes:
  redis-data:
  postgres-data:
